# Generated by Django 5.0.4 on 2024-04-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_authtempcode_created_at_authtempcode_retry_attempts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authtempcode',
            options={'verbose_name': 'Одноразовый код входа', 'verbose_name_plural': 'Одноразовые коды входа'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(max_length=6, null=True, verbose_name='Реферальный код'),
        ),
    ]
